//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentals
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentalDB5Entities : DbContext
    {
        public CarRentalDB5Entities()
            : base("name=CarRentalDB5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rental_Records> Rental_Records { get; set; }
        public virtual DbSet<Type_Of_Car> Type_Of_Car { get; set; }
        public string CustomerName { get; internal set; }
    }
}
