//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental_Records
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> TypeOfCarID { get; set; }
    
        public virtual Type_Of_Car Type_Of_Car { get; set; }
    }
}
